---
title: "transcriptomics_day1_ankur"
format: html
---

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")

cran_pkgs <- c("tidyverse", "pheatmap")
bioc_pkgs <- c("DESeq2", "clusterProfiler", "Rsubread", "systemPipeRdata", "Rqc", "QuasR")
```

```{r}
#| eval: false
new_pkgs <- c(cran_pkgs, bioc_pkgs)[!(c(cran_pkgs, bioc_pkgs) %in% installed.packages()[,"Package"])]
if(length(new_pkgs)) BiocManager::install(new_pkgs, update = FALSE)

```

```{r}

lapply(c(cran_pkgs, bioc_pkgs), library, character.only = TRUE)
```

```{bash}
mkdir -p data/data_ankur/reference data/data_ankur/raw data/data_ankur/trimmed

# Download TAIR10.1
wget -nc https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz -P data/data_ankur/reference/
wget -nc https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.gtf.gz -P data/data_ankur/reference/
gunzip data/data_ankur/reference/*.gz
```
```{r}
library(systemPipeRdata)
fq_path <- systemPipeRdata::pathList()$fastqdir
file.copy(list.files(fq_path, full.names = TRUE), "data/data_ankur/raw/")
```

```{bash}
gunzip data/data_ankur/raw/*.gz
```

```{r}
#library(Rqc)
raw_files <- list.files("data/data_ankur/raw", pattern = ".fastq", full.names = TRUE)
qc_res <- rqc(path = "data/data_ankur/raw", pattern = ".fastq", outdir = "reports/reports_ankur/rqc_raw")

```

```{r}
library(QuasR)

# Filter and output to 'trimmed' folder with new names
preprocessReads(filename = raw_files,
                outputFilename = paste0("data/data_ankur/trimmed/", basename(raw_files), ".trimmed.fastq"),
                truncateEndBases = 3, 
                minLength = 30)
```

```{r}
# Reference and Index paths
ref_genome <- "data/data_ankur/reference/GCF_000001735.4_TAIR10.1_genomic.fna"
index_prefix <- "data/data_ankur/reference/athal_index"

# Drive the terminal using R: 8 CPUs for speed
system2("hisat2-build", args = c("-p 8", ref_genome, index_prefix))
```

```{bash}
hisat2 -h

```
```{r}
#system2(hisat2 -x data/data_ankur/reference/athal_index -U SRR446027_1.fastq )
#system2("hisat2-build", args = c("-p 8", ref_genome, index_prefix, -x data/data_ankur/reference/athal_index, -U SRR446027_1.fastq ))
#system2("hisat2-build", args = c("-p 8", ref_genome, index_prefix))


system2("hisat2", args = c("-p 8","-x data/data_ankur/reference/athal_index","-U data/data_ankur/raw/SRR446027_1.fastq", "-S data/data_ankur/stdout.bam"))
```

