---
title: "transcriptomics_day4_Krish"
author: "Krish Desai"
format: html
editor: visual
---

# **Part 0: Computational Environment**

```{r}
#| echo: false
# Check and install missing critical packages if they don't exist
if (!requireNamespace("org.At.tair.db", quietly = TRUE)) BiocManager::install("org.At.tair.db", update = FALSE)
if (!requireNamespace("viridis", quietly = TRUE)) install.packages("viridis")

# Define the required packages
# clusterProfiler: For GO enrichment
# org.At.tair.db: The Arabidopsis annotation database
# viridis: For colorblind-friendly palettes
pkgs <- c("tidyverse", "DESeq2", "pheatmap", "EnhancedVolcano", 
          "clusterProfiler", "org.At.tair.db", "RColorBrewer", "viridis")

# Load all packages efficiently using lapply
lapply(pkgs, library, character.only = TRUE)


# Load your dds_results and count matrix from Day 3
# Ensure these objects are in your environment before proceeding
print("Biological Discovery Environment: READY")
```

# **Part 1: The Volcano Plot**

```{r}
res_1h_12h <- read.csv("data/Data_Krish/sig_virulent_genes_res_1_12.csv", row.names = 1)
res_1h_6h <- read.csv("data/Data_Krish/sig_virulent_genes_res_1_6.csv", row.names = 1)
res_6h_12h <- read.csv("data/Data_Krish/sig_virulent_genes_res_6_12.csv", row.names = 1)
filtered_res_1h_12h <- read.csv("data/Data_Krish/sig_virulent_genes_filteredres_1_12.csv", row.names = 1)
filtered_res_1h_6h <- read.csv("data/Data_Krish/sig_virulent_genes_filteredres_1_6.csv", row.names = 1)
filtered_res_6h_12h <- read.csv("data/Data_Krish/sig_virulent_genes_filteredres_6_12.csv", row.names = 1)


EnhancedVolcano(res_1h_12h,
                lab = rownames(res_1h_12h),
                x = 'log2FoldChange',
                y = 'padj',
                title = 'Time Series: 1h vs. 12h',
                pCutoff = 0.2, 
                FCcutoff = 1.0,
                pointSize = 3.0,
                labSize = 4.0)

EnhancedVolcano(res_1h_6h,
                lab = rownames(res_1h_6h),
                x = 'log2FoldChange',
                y = 'padj',
                title = 'Time Series: 1h vs. 6h',
                pCutoff = 0.2, 
                FCcutoff = 1.0,
                pointSize = 3.0,
                labSize = 4.0)

EnhancedVolcano(res_6h_12h,
                lab = rownames(res_6h_12h),
                x = 'log2FoldChange',
                y = 'padj',
                title = 'Time Series: 6h vs. 12h',
                pCutoff = 0.2, 
                FCcutoff = 1.0,
                pointSize = 3.0,
                labSize = 4.0)
```

# **Part 2: The Heatmap and Z-Scores**

```{r}
# 1. Extract the VST-transformed counts for your significant 1h vs 12h genes
# Assuming your filtered object is named 'sig_1h_12h'
plot_mat_1h <- assay(vsd2)[c(rownames(filtered_res_1h_12h),row.names(filtered_res_1h_6h)[-which(row.names(filtered_res_1h_6h)==row.names(filtered_res_1h_12h))]), ]

# 2. Create the Heatmap
pheatmap(plot_mat_1h, 
         scale = "row", 
         clustering_distance_rows = "euclidean",
         clustering_method = "complete",
         color = magma(100), 
         show_colnames = TRUE,
         main = "Significant Genes: 1h vs 12h")


plot_mat_6h <- assay(vsd2)[rownames(filtered_res_1h_6h), ]

# 2. Create the Heatmap
pheatmap(plot_mat_6h, 
         scale = "row", 
         clustering_distance_rows = "euclidean",
         clustering_method = "complete",
         color = magma(100), 
         show_colnames = TRUE,
         main = "Significant Genes: 1h vs 6h")

plot_mat_12h <- assay(vsd2)[rownames(filtered_res_6h_12h), ]

# 2. Create the Heatmap
pheatmap(plot_mat_12h, 
         scale = "row", 
         clustering_distance_rows = "euclidean",
         clustering_method = "complete",
         color = magma(100), 
         show_colnames = TRUE,
         main = "Significant Genes: 6h vs 12h")
```
