---
title: "transcriptomics_day4_kimia"
author: "Kimia"
format: html
editor: visual
toc: true
---

# **The basics of transcriptomics pt4**

## **Part 0: Computational Environment**

```{r}
#| message: false
#| warning: false
# Check and install missing critical packages if they don't exist
if (!requireNamespace("org.At.tair.db", quietly = TRUE)) BiocManager::install("org.At.tair.db", update = FALSE)
if (!requireNamespace("viridis", quietly = TRUE)) install.packages("viridis")

# Define the required packages
# clusterProfiler: For GO enrichment
# org.At.tair.db: The Arabidopsis annotation database
# viridis: For colorblind-friendly palettes
pkgs <- c("tidyverse", "DESeq2", "pheatmap", "EnhancedVolcano", 
          "clusterProfiler", "org.At.tair.db", "RColorBrewer", "viridis")

# Load all packages efficiently using lapply
lapply(pkgs, library, character.only = TRUE)
```

## **Part 1: The Volcano Plot**

1.  Generate a Volcano plot for your 1h vs. 6h results.

2.  Visually identify if the “mountain” of genes looks broader or narrower than the 12h comparison.

**Bonus:** Do it for 6h vs 12h

```{r}
EnhancedVolcano(res_1h_12h,
                lab = rownames(res_1h_12h),
                x = 'log2FoldChange',
                y = 'padj',
                title = 'Time Series: 12h vs. 1h',
                pCutoff = 0.2, 
                FCcutoff = 1.0,
                pointSize = 3.0,
                labSize = 4.0)
```

```{r}
EnhancedVolcano(res_1h_6h,
                lab = rownames(res_1h_6h),
                x = 'log2FoldChange',
                y = 'padj',
                title = 'Time Series: 1h vs. 6h',
                pCutoff = 0.2, 
                FCcutoff = 1.0,
                pointSize = 3.0,
                labSize = 4.0)
```

```{r}

```
